# Generated by Django 4.2.1 on 2023-05-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_available_book_statue'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
